import { StyleSheet } from "react-native";

export const BookingStyles = StyleSheet.create({
  titleContainer: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
  },
  title: {
    fontWeight: 700,
    fontSize: 24,
    color: "#040152",
  },
  container: {
    alignItems: "center",
    backgroundColor: "#F5F8FF",
    paddingTop: 20,
  },
  toggleContainer: {
    width: 350,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  toggleButton: {
    paddingHorizontal: 40,
    paddingVertical: 10,
    borderTopRightRadius: 10,
    marginBottom: 20,
  },
  toggleButtonStyle: {
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 40,
    paddingVertical: 10,
    borderTopRightRadius: 10,
    marginBottom: 20,
  },
  toggleButtonStyles: {
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 40,
    paddingVertical: 10,
    borderTopLeftRadius: 10,
    marginBottom: 20,
  },
  toggleButtonText: {
    fontWeight: 700,
    fontSize: 14,
    lineHeight: 21,
    color: "#040152",
  },
  productContainer: {
    marginBottom: 20,
    padding: 10,
    width: 350,
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#B6B6B6",
    flexDirection: "row",
    alignItems: "center",
    // justifyContent: "space-between",
    gap: 8,
  },
  iconBox: {
    width: 50,
    height: 50,
    padding: 8,
    borderRadius: 50,
    backgroundColor: "#F5F8FF",
  },
  icon: {
    borderRadius: 50,
    width: "100%",
    height: "100%",
  },
  textContainer: {
    width: 188,
  },
  placeTitle: {
    fontSize: 14,
    lineHeight: 21,
    fontWeight: "bold",
    marginBottom: 6,
    color: "#040152",
  },
  bookingDates: {
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "bold",
    marginBottom: 6,
    color: "#040152",
  },
  deskAndTableBox: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  totalDesk: {
    fontSize: 10,
    lineHeight: 15,
    fontWeight: "bold",
    marginBottom: 6,
    color: "rgba(4, 1, 82, 0.53)",
    backgroundColor: "#F5F8FF",
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  totalCabin: {
    fontSize: 10,
    lineHeight: 15,
    fontWeight: "bold",
    marginBottom: 6,
    color: "rgba(4, 1, 82, 0.53)",
    backgroundColor: "#F5F8FF",
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  totalAmount: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "bold",
    marginBottom: 6,
    color: "#040152",
    textAlign: "right",
    width: 70,
  },
});
